# Generated by Django 6.0 on 2026-05-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
                ('fee', models.FloatField()),
            ],
        ),
    ]
